### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mobatusi** [activityMonitoring/biobankAccelerometerAnalysis#133] opened 2021-03-30 14:11 UTC
Please add cd biobankAccelerometerAnalysis in the installation instructions after "git clone git@github.com:activityMonitoring/biobankAccelerometerAnalysis.git" Otherwise the person following the instructions may not be aware that this step to be in the biobankAccelerometerAnalysis directory to run the following step of "bash utilities/downloadDataModels.sh" Thank you!

**Comment by angerhang** [comment] 2021-04-01 10:58
Thanks for reporting @mobatusi . This looks like a duplicate of https://github.com/activityMonitoring/biobankAccelerometerAnalysis/issues/128 and a PR has already been submitted, thus closing.

**Closed by angerhang** 2021-04-01 10:58 UTC
Labels: enhancement
